cursor_shape block
font_family JetbrainsNerdFont
font_size 12
include ~/.cache/wal/colors-kitty.conf
background_opacity 0.2
confirm_os_window_close 0

window_padding_width 4

startup_session startup.conf

